disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - identifier_name
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
